[build]
  command = "ng build --configuration production && npm run json-server"
  publish = "dist/zenquna"

[dev]
  command = "ng serve"
  port = 4200
    publish = "dist/zenquna"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200