[build]
  command = "ng build --configuration production"
  publish = "dist/zenquna"

[dev]
  command = "ng serve"
  port = 4200
    publish = "dist/zenquna"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200